allowBuilds:
  esbuild: true
overrides:
  brace-expansion: "^1.1.13" # GHSA-f886-m6hf-6m8v
  minimatch: "^3.1.4" # GHSA-23c5-xmqv-rm74 等
  flatted: "^3.4.2" # GHSA-25h7-pfq9-p65f, GHSA-rf6f-7fwh-wjgh
  ajv: "^6.14.0" # GHSA-2g4f-4pwh-qvx6
